# Generated by Django 2.0.7 on 2018-07-30 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField()),
                ('buy_game', models.CharField(max_length=200)),
                ('batting_ratio', models.FloatField()),
                ('batting_money', models.IntegerField()),
                ('folder_num', models.IntegerField()),
                ('win_check', models.IntegerField()),
                ('etc_memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinBook_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=200)),
                ('memo', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
