# Generated by Django 2.0.7 on 2018-07-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0004_auto_20180730_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='theaterwinbookrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='batting_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='batting_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='buy_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='folder_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='win_check',
            field=models.IntegerField(default=0),
        ),
    ]
