# Generated by Django 2.0.7 on 2018-07-30 12:25

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0005_auto_20180730_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaterwinbookrecord',
            old_name='buy_game',
            new_name='buy_game_title',
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='buy_date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='etc_memo',
            field=models.TextField(blank=True),
        ),
    ]
