# Generated by Django 2.0.7 on 2018-08-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0008_auto_20180802_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='win_check',
            field=models.IntegerField(default=1),
        ),
    ]
