# Generated by Django 2.1.2 on 2018-12-24 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0010_theaterwinbookrecord_writing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('question_title', models.CharField(blank=True, max_length=200)),
                ('question_content', models.TextField(blank=True)),
                ('question_isanswer', models.IntegerField(blank=True, default=0)),
                ('question_thumbup', models.IntegerField(default=0)),
                ('question_hit', models.IntegerField(default=0)),
                ('queston_groupnum', models.IntegerField(default=0)),
                ('question_sequencenum_ingroup', models.IntegerField(default=0)),
                ('question_level_ingorup', models.IntegerField(default=0)),
                ('etc_memo', models.CharField(blank=True, max_length=200)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
