# Generated by Django 2.1.2 on 2018-12-24 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0011_theaterwinquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
