# Generated by Django 2.1.2 on 2018-12-24 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0013_theaterwinquestion_question_thumbup2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterwinquestion',
            name='question_thumbup2',
        ),
    ]
