# Generated by Django 2.1.4 on 2019-01-01 07:00

from django.db import migrations, models
import django.utils.datetime_safe
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0014_remove_theaterwinquestion_question_thumbup2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaterwinquestion',
            old_name='queston_groupnum',
            new_name='question_groupnum',
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_hit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_thumbup',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='writing_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
