# Generated by Django 2.0.7 on 2019-01-02 11:27

from django.db import migrations, models
import django.utils.datetime_safe
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0015_auto_20190101_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='WysiwygModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_isanswer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='question_thumbup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theaterwinquestion',
            name='writing_date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
