# Generated by Django 2.0.7 on 2019-01-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0016_auto_20190102_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hit', models.IntegerField(default=0)),
                ('question_thumbup', models.IntegerField(default=0)),
                ('question_thumbdown', models.IntegerField(default=0)),
                ('question_warning', models.IntegerField(default=0)),
                ('by_whom', models.CharField(max_length=200)),
                ('question_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinQuestion')),
            ],
        ),
        migrations.DeleteModel(
            name='WysiwygModel',
        ),
    ]
