# Generated by Django 2.1.2 on 2019-01-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0017_auto_20190115_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterwinquestioninfo',
            name='question_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinQuestion', unique=True),
        ),
    ]
