# Generated by Django 2.0.7 on 2019-01-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0018_auto_20190116_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterwinquestioninfo',
            name='question_fk',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinQuestion'),
        ),
    ]
