# Generated by Django 2.0.7 on 2019-01-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0021_auto_20190117_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinQuestionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('question_reply_content', models.CharField(max_length=200)),
                ('question_reply_thumbup', models.IntegerField(default=0)),
                ('question_reply_thumbdown', models.IntegerField(default=0)),
                ('question_reply_warning', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinQuestion')),
            ],
        ),
    ]
