# Generated by Django 2.0.7 on 2019-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0023_auto_20190127_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterwinquestion',
            name='question_thumbdown',
        ),
        migrations.RemoveField(
            model_name='theaterwinquestion',
            name='question_thumbup',
        ),
    ]
