# Generated by Django 2.0.7 on 2019-02-08 01:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0025_full_chatting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='theaterwinbookrecord',
            name='batting_analysis',
            field=tinymce.models.HTMLField(default='내용없음', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='theaterwinbookrecord',
            name='share_check',
            field=models.IntegerField(default=0),
        ),
    ]
