# Generated by Django 2.0.7 on 2019-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0026_auto_20190208_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='theaterwinbookrecord',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
