# Generated by Django 2.0.7 on 2019-02-08 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0027_theaterwinbookrecord_hit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinBookRecordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_thumbup', models.IntegerField(default=0)),
                ('record_thumbdown', models.IntegerField(default=0)),
                ('record_warning', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinBookRecord')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinBookRecordReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('record_reply_content', models.CharField(max_length=200)),
                ('record_groupnum', models.IntegerField(default=0)),
                ('record_sequencenum_ingroup', models.IntegerField(default=0)),
                ('record_level_ingorup', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.TheaterWinBookRecord')),
            ],
        ),
    ]
