# Generated by Django 2.0.7 on 2019-02-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0028_theaterwinbookrecordinfo_theaterwinbookrecordreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterwinbookrecord',
            name='hit_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
